POST http://localhost:3004/api/users/
Content-Type: application/json

{
    "username": "diniez",
    "name": "Superuser",
    "password": "tiara"
}

###
POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "diniez",
    "password": "tiaratania"
}