POST http://localhost:3004/api/users/
Content-Type: application/json

{
    "username": "beef",
    "name": "tiara",
    "password": "beef"
}

### login as tiara
POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "tiara",
    "password": "tiara"
}

### login as beef
POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "beef",
    "password": "beef"
}


