POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "username": "superuser",
    "name": "superuser",
    "password": "password"
}

### login as tiara
POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "viswa",
    "password": "viswa"
}

### login as beef
POST http://localhost:3004/api/login
Content-Type: application/json

{
    "username": "beef",
    "password": "beef"
}


