POST http://localhost:3004/api/blogs/
Content-Type: application/json

{
    "title": "test w/ user",
    "author": "dinie zikry rudi",
    "url": "dinie.com",
    "likes": 69,
    "userId": "61ee8e77af590b3ffc8c37ed"
}
###
POST http://localhost:3004/api/blogs/
Content-Type: application/json

{
    "title": "how to be a web dev",
    "author": "dinie zikry rudi",
    "url": "dinie.com",
    "likes": 100,
    "userId": "61ee8e77af590b3ffc8c37ed"
}